imxrt106x: create script with basic commands and attach it to .data section in plo image
phoenix-rtos/phoenix-rtos-project pull request #29
Opened 2020-10-26 13:29 UTC by HBuczynski

2020-10-26 13:46 UTC, agkaminski requested changes

2020-10-26 13:46 UTC, agkaminski commented on _targets/build.project.armv7m7-imxrt106x
> +	echo "00" >> $PREFIX_BUILD/plo/script.plo
Replace with '\0'

2020-10-26 14:03 UTC, HBuczynski commented on _targets/build.project.armv7m7-imxrt106x
> +	echo "00" >> $PREFIX_BUILD/plo/script.plo
Done

2020-10-26 15:19 UTC, kemonats commented on _targets/build.project.armv7m7-imxrt106x
> +		echo @$prog\($(printf "%x" $poffs):$(printf "%x" $psz)\) >> $PREFIX_BUILD/plo/script.plo
simply one printf
```bash
printf "@%s(%x:%x)\n" $prog $poffs $psz >> $PREFIX_BUILD/plo/script.plo
```

2020-10-26 15:19 UTC, kemonats commented on _targets/build.project.armv7m7-imxrt106x
> +	echo "$(cat _targets/armv7m7-imxrt106x.plo)" >> $PREFIX_BUILD/plo/script.plo
only cat is needed
```bash
cat _targets/armv7m7-imxrt106x.plo >> $PREFIX_BUILD/plo/script.plo
```

2020-10-27 10:49 UTC, HBuczynski commented on _targets/build.project.armv7m7-imxrt106x
> +		echo @$prog\($(printf "%x" $poffs):$(printf "%x" $psz)\) >> $PREFIX_BUILD/plo/script.plo
Done

2020-10-27 10:49 UTC, HBuczynski commented on _targets/build.project.armv7m7-imxrt106x
> +	echo "$(cat _targets/armv7m7-imxrt106x.plo)" >> $PREFIX_BUILD/plo/script.plo
Done

2020-10-27 10:53 UTC, agkaminski commented on _targets/build.project.armv7m7-imxrt106x
> +	b_log "Relink plo to include newly script"
*new script

2020-10-27 11:52 UTC, merged