ci: add nightly workflow
phoenix-rtos/phoenix-rtos-project pull request #730
Opened 2023-05-16 17:17 UTC by jsarzy

## Description
Add nightly CI that will be run at 1 am. It includes long tests such as busybox or micropython test suit. I turned regular workflow into callable with the nightly argument.

It needs PR from phoenix-rtos-tests so I will merge it by myself. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: ia32-generic.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-05-17 11:34 UTC, jsarzy commented on .github/workflows/nightly.yml
> +    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/ci-project.yml@jsarzy/nightly
must be changed to master before merging

2023-05-17 12:03 UTC, jsarzy commented
Must wait for https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/200

["nightly" workflow triggered manually](https://github.com/phoenix-rtos/phoenix-rtos-project/actions/runs/5002669885) (it's expected to fail)

2023-05-29 10:58 UTC, damianloew requested changes
Looks good to me, I'd like to see only the current results (for example triggered on `pull_request` event - if everything was ok we could change branches to master and merge it)

2023-05-30 09:12 UTC, jsarzy commented on .github/actions/phoenix-runner/action.yml
> +      - ${{ inputs.nightly == 'true' && '--nightly' || format('-T{0}', inputs.target) }}
I think the best solution here is to use `argpasrse.BooleanOptionalAction` in the python script. With that you can just pass `--no-nightly` flag. However, this requires python >= 3.9.

2023-06-15 12:31 UTC, nalajcie approved these changes

2023-06-15 12:32 UTC, merged