armv7a9-qemu: Adjust serial device
phoenix-rtos/phoenix-rtos-project pull request #997
Opened 2024-02-02 08:20 UTC by maska989

JIRA: CI-397

## Description

In the process of creating a test that check's Control Codes, there is a problem with our QEMU setup. 
qemu-system-aarch64 with machine arm-generic-fdt-7series have multiple serials outputs. First one is responsible for VNC connection. Second one is strictly connected with emulated environment. Redirecting it to `mon:stdio` give us access to use QEMU shortcuts which they collide with our tests. Even in further use cases, this will be a problem.
Shortcuts available with serial output set on to `mon:stdio`:

![image](https://github.com/phoenix-rtos/phoenix-rtos-project/assets/49757239/e90be0d2-861a-4601-8f48-de92e4f06b24)

To minimize interference from QEMU side, we can simply redirect serial directly on stdio and solve this problem.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: armv7a9-zynq7000-qemu.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing linter checks and tests passed.
- [X] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2024-04-29 07:57 UTC, maska989 commented
@nalajcie Thanks for perfect advice. Added new pr on phoenix-rtos-test submodule to utilize this change. This will impact less for people using QEMU as they desired.

2024-09-26 08:01 UTC, damianloew approved these changes

2024-09-26 08:03 UTC, damianloew requested changes
Please correct the commit message. You are just adding a new script for testing purposes and in the commit description please leave an information why is it needed

2024-09-26 10:50 UTC, damianloew approved these changes

2024-09-26 10:51 UTC, merged

2024-09-26 11:46 UTC, nalajcie commented
there was a change to the source script in the meantime (https://github.com/phoenix-rtos/phoenix-rtos-project/commit/90c36f8f09e347419a886c0ea2bbfc6423329226). Is it conscious choice (different DTB)?